print("First code from master branch")
print ("new file")
print ("second code from master branch")
print ("second file")
print ("third code from master branch")
print ("3rd file")
print ("4th code from master branch")
print ("5th code from second branch")
print ("5th file")